export interface Country {
  code: string;
  name: string;
  flag: string;
  dialCode: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", dialCode: "93" },
  { code: "AL", name: "Albania", flag: "🇦🇱", dialCode: "355" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", dialCode: "213" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", dialCode: "54" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", dialCode: "374" },
  { code: "AU", name: "Australia", flag: "🇦🇺", dialCode: "61" },
  { code: "AT", name: "Austria", flag: "🇦🇹", dialCode: "43" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", dialCode: "994" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", dialCode: "973" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", dialCode: "375" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", dialCode: "32" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", dialCode: "501" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", dialCode: "229" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", dialCode: "975" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", dialCode: "591" },
  { code: "BA", name: "Bosnia & Herzegovina", flag: "🇧🇦", dialCode: "387" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", dialCode: "55" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", dialCode: "673" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", dialCode: "359" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", dialCode: "855" },
  { code: "CA", name: "Canada", flag: "🇨🇦", dialCode: "1" },
  { code: "CL", name: "Chile", flag: "🇨🇱", dialCode: "56" },
  { code: "CN", name: "China", flag: "🇨🇳", dialCode: "86" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", dialCode: "57" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", dialCode: "385" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", dialCode: "53" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", dialCode: "357" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", dialCode: "420" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", dialCode: "45" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", dialCode: "20" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", dialCode: "372" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", dialCode: "251" },
  { code: "FI", name: "Finland", flag: "🇫🇮", dialCode: "358" },
  { code: "FR", name: "France", flag: "🇫🇷", dialCode: "33" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", dialCode: "995" },
  { code: "DE", name: "Germany", flag: "🇩🇪", dialCode: "49" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", dialCode: "233" },
  { code: "GR", name: "Greece", flag: "🇬🇷", dialCode: "30" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", dialCode: "36" },
  { code: "IN", name: "India", flag: "🇮🇳", dialCode: "91" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", dialCode: "62" },
  { code: "IR", name: "Iran", flag: "🇮🇷", dialCode: "98" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", dialCode: "964" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", dialCode: "353" },
  { code: "IL", name: "Israel", flag: "🇮🇱", dialCode: "972" },
  { code: "IT", name: "Italy", flag: "🇮🇹", dialCode: "39" },
  { code: "JP", name: "Japan", flag: "🇯🇵", dialCode: "81" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", dialCode: "962" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", dialCode: "7" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", dialCode: "254" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", dialCode: "965" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", dialCode: "996" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", dialCode: "371" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", dialCode: "961" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", dialCode: "370" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", dialCode: "352" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", dialCode: "389" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", dialCode: "60" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", dialCode: "960" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", dialCode: "52" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", dialCode: "373" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", dialCode: "976" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", dialCode: "382" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", dialCode: "212" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", dialCode: "95" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", dialCode: "977" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", dialCode: "31" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", dialCode: "64" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", dialCode: "234" },
  { code: "NO", name: "Norway", flag: "🇳🇴", dialCode: "47" },
  { code: "OM", name: "Oman", flag: "🇴🇲", dialCode: "968" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", dialCode: "92" },
  { code: "PS", name: "Palestine", flag: "🇵🇸", dialCode: "970" },
  { code: "PE", name: "Peru", flag: "🇵🇪", dialCode: "51" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", dialCode: "63" },
  { code: "PL", name: "Poland", flag: "🇵🇱", dialCode: "48" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", dialCode: "351" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", dialCode: "974" },
  { code: "RO", name: "Romania", flag: "🇷🇴", dialCode: "40" },
  { code: "RU", name: "Russia", flag: "🇷🇺", dialCode: "7" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", dialCode: "966" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", dialCode: "381" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", dialCode: "65" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", dialCode: "421" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", dialCode: "386" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", dialCode: "252" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", dialCode: "27" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", dialCode: "82" },
  { code: "ES", name: "Spain", flag: "🇪🇸", dialCode: "34" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", dialCode: "94" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", dialCode: "249" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", dialCode: "46" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", dialCode: "41" },
  { code: "SY", name: "Syria", flag: "🇸🇾", dialCode: "963" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", dialCode: "886" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", dialCode: "992" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", dialCode: "255" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", dialCode: "66" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", dialCode: "216" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", dialCode: "90" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", dialCode: "993" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", dialCode: "256" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", dialCode: "380" },
  { code: "AE", name: "UAE", flag: "🇦🇪", dialCode: "971" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", dialCode: "44" },
  { code: "US", name: "United States", flag: "🇺🇸", dialCode: "1" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", dialCode: "598" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", dialCode: "998" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", dialCode: "58" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", dialCode: "84" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", dialCode: "967" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", dialCode: "263" },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}

export function detectCountryFromPhone(phone: string): Country | undefined {
  if (!phone.startsWith("+")) return undefined;
  const digits = phone.slice(1);
  const sorted = [...COUNTRIES].sort((a, b) => b.dialCode.length - a.dialCode.length);
  return sorted.find(c => digits.startsWith(c.dialCode));
}
